config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  patch 'users/:id', to: 'users#update', as: 'update_user'
    resources :books, only: [:new, :index, :show, :destroy, :update, :edit, :create]
    resources :user, only: [:edit, :show, :update]
  get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :caption, presence: true


 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  validates :name, length: { minimum: 2 }
   validates :name, length: { maximum: 20 }
   validates :introduction, length: { maximum: 50 }
   
  has_one_attached :image  
  has_one_attached :profile_image

  validates :name, presence: true
  validates :name, uniqueness: true
    
 
         
 def get_image
    if image.attached?
      image.variant(resize: "100x100")
    else
      'no_image.jpg'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    books_path
  end
  
    def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 def new
    @book = Book.new
  end


  def show
    @user = User.all
    @book = Book.find(params[:id])
    @books = Book.page(params[:page])
  rescue ActiveRecord::RecordNotFound
  flash[:alert] = "Book not found"
  redirect_to user_path
  end

   def index
    @booker = current_user
    @book = Book.new
    @books = Book.page(params[:page])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    flash[:notice] = "投稿を削除しました"
    redirect_to books_path
  end

  def update
     @book = Book.find(params[:id])
  if @book.update(book_params)
    redirect_to books_path
    flash[:notice] = "プロフィール編集に成功しました"
  else
    render books_path
  end
 end

  def edit
    @book = Book.find(params[:id])  
  end

  def create
    @book = current_user.books.build(book_params)
    @books= Book.all
   if @book.save
    redirect_to books_path
    flash[:notice] = "投稿に成功しました"
   else
    @books = Book.page(params[:page])
    flash[:notice] = '投稿に失敗しました'
    render :index
   end
  end
  
  
    private
      
   def user_params
    params.permit(:id, :image)
   end
    

  def book_params
    params.require(:book).permit(:title, :caption, :id, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @users = User.all
    @book = Book.find(params[:name])
    @books = Book.page(params[:page])
  rescue ActiveRecord::RecordNotFound
  flash[:alert] = "Book not found"
  end
  
  def index
    @user = User.all
    @book = Book.new
    @books = Book.page(params[:page])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to books_path(current_user)
     flash[:notice] = "プロフィール編集に成功しました"
  else
    flash[:notice] = "プロフィール編集に失敗しました"
    @users = User.all
    render :show
  end 
end

  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @book = current_user.books.build(book_params)
    @books= Book.all
   if @book.save
    redirect_to books_path
    flash[:notice] = "投稿に成功しました"
   else
    @books = Book.page(params[:page])
    flash[:notice] = '投稿に失敗しました'
    render :index
   end
  end
  
   private
  
  def user_params
  params.require(:user).permit(:name, :introduction, :email, :image)
end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @book do |f| %>
  <label for="title">Title</label>
  <%= f.text_field :title, placeholder: "タイトル" %>
  <label for="caption">caption</label>
  <%= f.text_field :caption, placeholder: "内容" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/books/index.html.erb
<html>
  <head>

  </head>
  
<div class = "book">
  <div class = "body">
<%= flash[:notice] %>
<div class = "profile">

<p><%= image_tag current_user.get_image %></p>

<h1><%= current_user.name %></h1>

<h2>introduction: <%= current_user.introduction %></h2>

</div>
<set>
<i class="fa-solid fa-user-pen"><%= link_to 'settig', edit_user_path(current_user) %>
</i>
</set>

<%= form_with model: @book do |f| %>
<h1>投稿</h1>
<% alert %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>caption</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>
</div>


<div class = 'main' >
<% @books.each do |book| %>
  <div class = 'main-content' >
    <div class = 'contents' >
    <p>title：<%= book.title %></p>
    <p>caption：<%= book.caption %></p>
    <p>name：<%= book.user.name %></p>
    </div>
    <div class = 'contents' >
   <% if book.user == current_user %>
     <%= link_to "edit", edit_book_path(book.id) %>
     <%= link_to 'delete', book, method: :delete %>
  <% end %>
  </div> 
  </div>
<% end %>

<%= paginate @books %>

</div>
</div>
</html>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<html>
  <head>

  </head>
  


<%= flash[:notice] %>

<body>
<%= form_with model: @book do |f| %>
<% alert %>
  <h4>name</h4>
  <%= f.text_field :title %>
  <h4>introduction</h4>
  <%= f.text_area :caption %>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit '投稿' %>
<% end %>

<div class = 'main' >

<% @user.each do |user| %>
  <div class='main-content'>
   <p><%= image_tag user.get_profile_image %></p>
    <p>name: <%= user.name %></p>
  </div>
<% end %>

</body>

</div>
</html>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/homes/about.html.erb
<about>
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>
</about>
<footer>
    CopyRight Infratop.inc
</footer>

app/views/homes/top.html.erb
<Home>
<h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers !!</strong></h1>
</br>
<h3>In <i class="fa-solid fa-book"></i>Bookers,</h3>
</br>
<h3>you can share and exchange your opinions , inpressions , </h3>
</br>
<h3>and emotions</h3>
</br>
<h3>about various books!</h3>

</Home>
<about>
<div class="btn-wrapper col-10 mx-auto">
       
        <a class="row" href="/users/sign_in">Log in</a>
      
        <a class="rows" href="/users/sign_up">Sign up</a>
 
</div>
</about>
<footer>
    CopyRight Infratop.inc
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/353e4c8b8d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <% if user_signed_in? %>
  <h3>
    
      <i class="fa-solid fa-house">
        <%= link_to "log out", destroy_user_session_path, method: :delete %>
      </i>
      <br/>
        <i class="fa-solid fa-house">
        <%= link_to "home", books_path %>
        </i>
        <br/>
        <i class="fa-solid fa-users">
       <%= link_to "user", user_path(current_user) %>
      </i>
      </h3>
    <% else %>
    <header>
    
    <i class="fa-solid fa-house">
        <%= link_to "home", root_path %>
    </i>
     </br>
    <i class="fa-solid fa-link">
     <%= link_to "about", homes_about_path %>
    </i>
     </br>
      <i class="fa-solid fa-user-plus">
        <%= link_to "sign up", new_user_registration_path %>
      </i>
      </br>
      <i class="fa-solid fa-right-to-bracket">
        <%= link_to "log in", new_user_session_path %>
      </i>
      
      </header>
    <% end %>
  </header>

    <%= yield %>
  </body>
</html>

app/views/user/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: current_user do |f| %>
<% alert %>
  <h4>name</h4>
  <%= f.text_field :name %>
  <h4>introduction</h4>
  <%= f.text_field :introduction %>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit '変更' %>
<% end %>

app/views/user/show.html.erb
<html>
  <head>

  </head>
  


<%= flash[:notice] %>
<h1><%= current_user.name %></h1>
<body>
<%= form_with model: current_user do |f| %>
<% alert %>
  <h4>name</h4>
  <%= f.text_field :name %>
  <h4>introduction</h4>
  <%= f.text_field :introduction %>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit '変更' %>
<% end %>

<div class = 'main' >
  <div class='main-content'>
  <% @users.each do |user| %>
  <div class='main-content'>
    <div class = 'contents' >
    <p><%= image_tag user.get_image %></p>
    <p>name: <%= user.name %></p>
    <p>introduction: <%=user.introduction  %></p>
    </div>
  </div>
</body>
<% end %>

</div>
</html>